### ISSUE TITLE
add  mention for themes that are compatible with libresprite 

### ISSUE THREAD

**Issue by tigercoding56** [aseprite/themes#15]

**Comment by dacap** [comment]
Sorry but we are not associated with the libresprite project.

**Comment by tigercoding56** [comment]
ok
i think you miss-understood
i meant to say on themes that are compatible with libresprite , of the themes you already have , you could put a notice in the description that they work with libresprite (fork of latest gpl-3 commit of asesprite )

------- Original Message -------
