### ISSUE TITLE
can't install theme

### ISSUE THREAD

**Issue by dafong** [aseprite/themes#5]
I am on mac ,I install JMSWRNR's Aseprite Themes follow the instructions, when I select theme,it says
"There is no default font", but I have installed the font "RobotoMono-Bold.ttf ", I am on macos

**Comment by QuipHop** [comment]
Same issue, Ubuntu 18.04

UPD:
/home/user/.config/aseprite/extensions/jmswrnr-dark-theme/theme.xml
Fixed by changing path to the file (which i copied here previously) 
`<font id="default" name="RobotoMono-Bold" type="truetype" file="./RobotoMono-Bold.ttf" antialias="true" size="6" />`

**Comment by dafong** [comment]
the author say will be fixed in next version v1.2.10
see here:   https://github.com/aseprite/aseprite/issues/1891

on Mac OS:
you can open /Users/xxx/Library/Application\ Support/Aseprite/extensions/jmswrnr-dark-theme/theme.xml
and replace the font with below
<font id="default" font="Aseprite" />
<font id="mini" font="Aseprite Mini" />
can temp solve the problem

**Comment by dacap** [comment]
The theme should work now on macOS on [v1.2.10-beta2](https://community.aseprite.org/t/aseprite-v1-2-10-beta2/2171) or with the fix of @QuipHop
